import {chromium} from '@playwright/test';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=process.env.EVIDENCE_DIR||'artifacts/polish-1';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chromium',headless:true});
const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:out+'/video',size:{width:1280,height:720}}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
await page.goto('http://127.0.0.1:5190/?test=1');await page.locator('[data-class="knight"]').click();await page.locator('[data-action="start"]').click();
await page.evaluate(()=>{const g=window.__ASHEN_GAME__;g.start(42);g.travel(g.rooms.find(r=>r.kind==='elite').id);const e=g.room.enemies.find(e=>e.kind==='elite');g.room.enemies=[e];g.player.x=510;g.cameraX=180;e.x=590;g.player.invuln=5;e.hp=e.maxHp=250;window.combatSamples=[];let previous=e.hp;window.sampleId=setInterval(()=>{if(e.hp!==previous){window.combatSamples.push({hp:e.hp,combo:g.attackCombo,progress:1-g.player.attack/g.attackDuration,armor:e.armorBroken,slash:g.effects.some(f=>f.kind==='slash')});previous=e.hp}},8)});
await page.keyboard.down('j');
for(let i=0;i<35;i++){const d=await page.evaluate(()=>{const g=window.__ASHEN_GAME__;return g.room.enemies[0].x-g.player.x;});await page.keyboard.up('d');await page.keyboard.up('a');if(Math.abs(d)>55)await page.keyboard.down(d>0?'d':'a');await page.waitForTimeout(120);}
await page.keyboard.up('d');await page.keyboard.up('a');await page.keyboard.up('j');
const elite=await page.evaluate(()=>{clearInterval(window.sampleId);const g=window.__ASHEN_GAME__,e=g.room.enemies[0];return {samples:window.combatSamples,armor:e.armorBroken,kills:g.kills,sound:g.sound.ctx?.state,phase:g.phase}});
assert(elite.armor);assert(elite.samples.some(s=>s.combo===3));assert(elite.samples.every(s=>s.slash&&s.progress>.35&&s.progress<.6));
await page.evaluate(async()=>{await window.__THREE_GAME_TEST_HOOKS__.setState('boss');const g=window.__ASHEN_GAME__,e=g.room.enemies.find(e=>e.kind==='boss');g.room.enemies=[e];e.x=690;g.player.x=600;g.cameraX=220;g.player.invuln=5;e.hp=e.maxHp*.56});
await page.keyboard.press('k');await page.keyboard.down('j');await page.waitForTimeout(2600);await page.keyboard.up('j');
const boss=await page.evaluate(()=>{const g=window.__ASHEN_GAME__,e=g.room.enemies.find(e=>e.kind==='boss');return {phase:e.bossPhase,hp:e.hp,souls:g.room.enemies.filter(e=>e.kind==='wraith').length,effects:g.effects.length,debris:g.debris.length}});assert.equal(boss.phase,2);assert.equal(boss.souls,0);
await page.screenshot({path:out+'/boss-motion-frame.png'});
await page.keyboard.press('Escape');await page.waitForTimeout(100);const audioPaused=await page.evaluate(()=>window.__ASHEN_GAME__.sound.ambience===null);assert(audioPaused);const video=page.video();await context.close();await copyFile(await video.path(),out+'/knight-motion.webm');
const mobile=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const mp=await mobile.newPage();await mp.goto('http://127.0.0.1:5190/?test=1');await mp.evaluate(async()=>{await window.__THREE_GAME_TEST_HOOKS__.setState('elite');window.__THREE_GAME_TEST_HOOKS__.setPausedForScreenshot(true)});await mp.screenshot({path:out+'/landscape-elite.png'});await mobile.close();await browser.close();
const result={elite,boss,audioPaused,errors};await writeFile(out+'/combat-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));assert.equal(errors.length,0);
